building html body
denmanma/html-resume pull request #2
Opened 2019-12-31 15:27 UTC by denmanma

2019-12-31 15:51 UTC, jonathan-irvin commented
Copy and paste your html into here: https://validator.w3.org/#validate_by_input and start by correcting the validation errors.

Usually, when you're doing stuff with React/Angular, the html won't always be valid, but since we're starting with the basics, you learn a lot by checking for valid HTML/CSS.

2019-12-31 15:56 UTC, jonathan-irvin requested changes
Other than some validation errors which will overlap with some of my comments, you're off to a good start!

2019-12-31 15:56 UTC, jonathan-irvin commented on resume.html
> +	325-277-2340 - denmanmd@gmail.com <a href='https://www.linkedin.com/in/michael-denman/'> LinkedIn Profile</a></br>
We can add hyperlinks for both your email and phone.

2019-12-31 15:56 UTC, jonathan-irvin commented on resume.html
> +	325-277-2340 - denmanmd@gmail.com <a href='https://www.linkedin.com/in/michael-denman/'> LinkedIn Profile</a></br>
For phones, prefix the link href with `tel:` and emails with `mailto:`
Try clicking on them after those changes.

2019-12-31 15:56 UTC, jonathan-irvin commented on resume.html
> +<h3>OCT 2005 - MONTH 2012</h3>
MONTH

2019-12-31 15:56 UTC, jonathan-irvin commented on resume.html
> +Windows-based test stations leading to over 99% up time of required machines.</br>
Is it up time or up-time?

2019-12-31 15:56 UTC, jonathan-irvin commented on resume.html
> +
</body>

2019-12-31 15:57 UTC, jonathan-irvin commented on resume.html
> +	325-277-2340 - denmanmd@gmail.com <a href='https://www.linkedin.com/in/michael-denman/'> LinkedIn Profile</a></br>
You'll be replacing https or http, so a phone would look like `<a href="tel:+13252772340">325-277-2340</a>`

2020-01-03 14:40 UTC, jonathan-irvin commented
@denmanma let's work on correcting these errors and getting this PR merged.

2020-01-03 14:48 UTC, denmanma commented on resume.html
> +Windows-based test stations leading to over 99% up time of required machines.</br>
up-time. good catch. I've had several people look over these bullets, and nobody has caught that.

2020-01-03 14:50 UTC, denmanma commented on resume.html
> +
What?

2020-01-03 15:06 UTC, denmanma commented on resume.html
> +
Turns out </br> is not acceptable. :P

2020-01-14 17:22 UTC, merged